routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard.index');

    // profile
    Route::get('/profile', 'HomeController@profile')->name('user.profile');
    Route::post('/profile', 'HomeController@editProfile')->name('user.editProfile');

    // end profile

    // sliders routes
    Route::get('sliders-data', 'SliderController@data')->name('sliders.data');
    Route::post('sliders-bulkDelete', 'SliderController@bulkDelete')->name('sliders.bulkDelete');
    Route::resource('sliders', 'SliderController')->except('show');
    //end sliders routes

    // about routes
    Route::get('about-data', 'AboutController@data')->name('about.data');
    Route::post('about-bulkDelete', 'AboutController@bulkDelete')->name('about.bulkDelete');
    Route::resource('about', 'AboutController')->except('show');
    //end about routes

    // customers routes
    Route::get('customers-data', 'CustomerController@data')->name('customers.data');
    Route::post('customers-bulkDelete', 'CustomerController@bulkDelete')->name('customers.bulkDelete');
    Route::resource('customers', 'CustomerController')->except('show');
    //end customers routes

    // blogs routes
    Route::get('blogs-data', 'BlogController@data')->name('blogs.data');
    Route::post('blogs-bulkDelete', 'BlogController@bulkDelete')->name('blogs.bulkDelete');
    Route::resource('blogs', 'BlogController')->except('show');
    //end customers routes

    // services routes
    Route::get('services-data', 'ServiceController@data')->name('services.data');
    Route::post('services-bulkDelete', 'ServiceController@bulkDelete')->name('services.bulkDelete');
    Route::resource('services', 'ServiceController')->except('show');
    //end services routes

    // projects routes
    Route::get('projects-data', 'ProjectController@data')->name('projects.data');
    Route::post('projects-bulkDelete', 'ProjectController@bulkDelete')->name('projects.bulkDelete');
    Route::resource('projects', 'ProjectController')->except('show');
    //end projects routes

    // contact routes
    Route::get('contact-us-data', 'ContactUsController@data')->name('contact-us.data');
    Route::post('contact-us-bulkDelete', 'ContactUsController@bulkDelete')->name('contact-us.bulkDelete');
    Route::resource('contact-us', 'ContactUsController')->except('show');
    //end contact routes

    // sections
    Route::get('sections-data', 'SectionController@data')->name('sections.data');
    Route::post('sections-bulkDelete', 'SectionController@bulkDelete')->name('sections.bulkDelete');
    Route::resource('sections', 'SectionController')->except('show');
    // end sections

    //pages
    Route::get('pages-data', 'PageController@data')->name('pages.data');
    Route::resource('pages', 'PageController')->except('show');
    //end pages

    // settings
    Route::get('settings', 'SettingController@index')->name('settings.index');
    Route::post('settings', 'SettingController@store')->name('settings.store');
    // end settings


});

routes/web.php
<?php

use App\Models\Page;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::namespace('website')->group(function () {

    // home
    Route::get('/', 'FrontController@index')->name('home');
    // end home

    // about
    Route::get('about', 'AboutController@index');
    // end about

    // services
    Route::get('services', 'ServiceController@index');
    Route::get('services/{id}', 'ServiceController@show');
    // end services

    // projects
    Route::get('projects', 'ProjectController@index');
    Route::get('projects/{id}', 'ProjectController@show');
    // end projects

    // blogs
    Route::get('blogs', 'BlogController@index');
    Route::get('blogs/{id}', 'BlogController@show');
    // end blogs

    //contact us
    $page_name = Page::where('url','/contact-us')->first()->name;
    Route::view('contact-us', 'website.pages.contact_us.index',compact('page_name'));
    Route::post('contact-us', 'ContactUsController@post')->name('website.contactUs');
    // end contact us
});

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
    protected $table = 'sections';

    protected $with = ['types'];

    protected $guarded = [];

    protected $appends = ['image'];

    public function photo()
    {
        return $this->morphOne(Photo::class, 'photoable');

    }//end of photo function

    public function getImageAttribute()
    {
        if ($this->photo == '') {
            return asset('default.svg');

        }
            return asset('images/sections/' . $this->photo->src);
    }//end of  function

    public function types(){
            return $this->hasMany(SectionType::class,'section_id','id');

    }//end of types function
}

app/Models/SectionType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SectionType extends Model
{
    protected $table ='section_types';
    protected $guarded = [];

    protected $appends = ['image'];

    public function section(){
        return $this->belongsTo(Section::class,'section_id');

    }//end of section function


    public function photo(){

        return $this->morphOne(Photo::class,'photoable');

    }//end of photo function

    public function getImageAttribute()
    {
        if ($this->photo == '') {
            return asset('default.svg');

        }
        return asset('images/section_types/' . $this->photo->src);
    }//end of  function
}

app/Http/Controllers/SectionController.php
<?php

namespace App\Http\Controllers;

use App\Helper\UploadTrait;

use App\Http\Requests\SectionRequest;
use App\Models\Photo;
use App\Models\Section;
use App\Models\SectionType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;
use ZipStream\File;

class SectionController extends Controller
{
    use UploadTrait;

    public function index()
    {

        return view('dashboard.sections.index');
    }


    public function create()
    {
        return view('dashboard.sections.create');
    }

    public function data()
    {
        $model = 'sections';
        $sections = Section::with('photo')->get();
        return DataTables::of($sections)
            ->addColumn('check_item', function ($raw) {
                return '<input type="checkbox" name="items[]" class="check_item" value="' . $raw->id . '">';
            })
            ->addColumn('photo', function ($raw) {
                return '<img width="100" height="80"  src="' . $raw->image . '" >';
            })
            ->addcolumn('actions', function ($raw) use ($model) {

                return view('dashboard.includes.actions', compact('raw', 'model'));
            })
            ->rawColumns(['photo' => 'photo', 'check_item' => 'check_item'])
            ->make(true);

    }//end of data function


    public function store(SectionRequest $request)
    {

        $data = $request->validated();

        unset($data['photo'], $data['type']);

        DB::beginTransaction();

        $section = Section::create($data);

        if ($request->hasFile('photo')) {
            $photo = $this->upload($request->photo, 'sections');
            $section->photo()->create([
                'src' => $photo,
                'type' => 'section',
            ]);
        };

        if($request->type){
            for ($x = 1; $x <= count($request->type); $x++) {

                $section_type = $section->types()->create([
                    'name' => $request->type[$x]['name'],
                    'content' => $request->type[$x]['content'],
                ]);

                if (array_key_exists('photo', $request->type[$x])) {
                    $photo = $this->upload($request->type[$x]['photo'], 'section_types');
                    $section_type->photo()->create([
                        'src' => $photo,
                        'type' => 'section_types',
                    ]);
                };
            };
        }



        DB::commit();
        return redirect()->route('sections.index')->with('success', 'تم إضافه البيانات بنجاح');

    }


    public function edit(Section $section)
    {


        return view('dashboard.sections.edit', compact('section'));
    }

    public function update(SectionRequest $request, Section $section)
    {


        $data = $request->validated();
        unset($data['photo']);
        DB::beginTransaction();
        $section->update($data);
        if ($request->hasFile('photo')) {
            $photo = $this->upload($request->photo, 'sections');
            $section->photo ? $this->deleteOldPhoto('images/sections/', $section->photo->src)
                & $section->photo()->update(['src' => $photo]) : $section->photo()->create(['src' => $photo, 'type' => 'section']);
        }


        for ($x = 1; $x <= count($request->type); $x++) {

            if (array_key_exists('id', $request->type[$x])) {

                $section_type = SectionType::findOrFail($request->type[$x]['id']);

                $section_type->update([
                    'name' => $request->type[$x]['name'],
                    'content' => $request->type[$x]['content'],
                ]);

                if (array_key_exists('photo', $request->type[$x])) {
                    if ($section_type->photo != '') {
                        $this->deleteOldPhoto('images/section_types', $section_type->photo->src);
                        $section_type->photo()->delete();
                    }

                    $photo = $this->upload($request->type[$x]['photo'], 'section_types');
                    $section_type->photo()->create([
                        'src' => $photo,
                        'type' => 'section_type'
                    ]);

                }
            } else {
                $section_type = $section->types()->create([
                    'name' => $request->type[$x]['name'],
                    'content' => $request->type[$x]['content'],
                ]);

                if (array_key_exists('photo', $request->type[$x])) {

                    $photo = $this->upload($request->type[$x]['photo'], 'section_types');
                    $section_type->photo()->create([
                        'src' => $photo,
                        'type' => 'section_type'
                    ]);

                }
            }


        }
        DB::commit();

        return redirect()->route('sections.index')->with('success', 'تم تعديل البيانات بنجاح');


    }


    public function destroy(Section $section)
    {
        $section->photo ? $this->deleteOldPhoto('images/sections/', $section->photo->src) & $section->photo()->delete() : '';
        Section::destroy($section->id);
        return redirect()->route('sections.index')->with('success', 'تم حذف البيانات بنجاح');
    }

    public function bulkDelete(Request $request)
    {
        foreach ($request->items as $item) {
            $section = Section::findOrFail($item);
            $this->destroy($section);
        }
        Section::destroy($request->items);
        return redirect()->route('sections.index')->with('success', 'تم حذف البيانات بنجاح');


    }//end of bulkDelete function
}

resources/views/dashboard/sections/create.blade.php
@extends('dashboard.layouts.master')
@section('content')
<div class="main-content side-content">
    <div class="container-fluid">
        <div class="inner-body">

            <form action="{{route('sections.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="card">
                    <div class="card-header">
                        <h3>إضافه سكشن</h3>
                    </div>
                    <div class="card-body pb-0">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-custom">
                                    <input type="text" name="section_name" class="form-control">
                                    <span class="input-span">إسم السشكن</span>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="input-custom">
                                    <input value="{{old('title')}}" type="text" name="title" class="form-control">
                                    <span class="input-span">العنوان</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-custom">
                                    <textarea name="content" rows="3"
                                        class="form-control editor">{{old('content')}}</textarea>
                                    <span class="input-span">المحتوي</span>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-custom">
                                    <label class="">الصورة ( مقاس الصورة -- 670 طول * 770 عرض )</label>
                                    <input id="photo" type="file" name="photo">
                                    <img width="100" id="preview" height="100" src="{{asset('default.svg')}}" alt="">
                                </div>
                            </div>
                        </div>
                        <hr>
                        <button id="add_type_btn" class="btn btn-warning"><i class="fa fa-plus"></i> إضافه نوع جديد
                        </button>
                        <br>
                        <div class="card-new" id="add_new_type"></div>
                    </div>
                    <div class="card-footer">
                        <button class="btn ripple btn-primary" type="submit"><i class="fe fe-save"></i> حفظ</button>
                    </div>
                </div>
            </form>

        </div>
    </div> <!-- End Main Content-->
</div> <!-- End Page -->
@endsection
@push('js')
<script>
    let count =1;
    $('#add_type_btn').on('click', function (e) {
        e.preventDefault();

        if(count > 5){
            Swal.fire({
                icon: 'error',
                title: 'عذراً ...',
                text: 'عدد الأنواع لابد أن يكون مساوياً  ل5  أو أقل !',

            })
        }else{
            let content = `
            <div class="card-content">
                <i class="fa fa-times delete_card"></i>
                <div class="row">
                    <div class="col-md-6">
                        <div class="input-custom">
                            <input type="text" class="form-control" name="type[${count}][name]">
                            <span class="input-span">الاسم</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="input-custom">
                            <input type="file" class="form-control" name="type[${count}][photo]">
                            <span class="input-span">الصوره</span>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="input-custom">
                            <input type="text" class="form-control" name="type[${count}][content]">
                            <span class="input-span">المحتوي</span>
                        </div>
                    </div>
                </div>
            </div>

        `;
            $('#add_new_type').append(content);
            count++
        }
    });


    $(document).on('click','.delete_card',function (){
        Swal.fire({
            title: 'هل أنت متأكد',
            text: "",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'نعم',
            cancelButtonText: 'لا'
        }).then((result) => {
            if (result.isConfirmed) {
                $(this).parent().remove();

                count--
                count = count < 1? 1 : count;

            }
        });

    });

</script>
@endpush

resources/views/dashboard/sections/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')
<div class="main-content side-content">
    <div class="container-fluid">
        <div class="inner-body">

            <form action="{{route('sections.update',$section->id)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')


                <div class="card">
                    <div class="card-header">
                        <h3>تعديل سكشن</h3>
                    </div>
                    <div class="card-body pb-0">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-custom">
                                    <input readonly value="{{$section->section_name}}" type="hidden" name="section_name"
                                        class="form-control">
                                    <span class="input-span d-none">إسم السشكن</span>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="input-custom">
                                    <input value="{{$section->title}}" type="text" name="title" class="form-control">
                                    <span class="input-span">العنوان</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-custom">
                                    <textarea name="content" rows="3"
                                        class="form-control editor">{{$section->content}}</textarea>
                                    <span class="input-span">المحتوي</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-custom">
                                    <label class="">الصورة ( مقاس الصورة -- 670 طول * 770 عرض )</label>
                                    <input id="photo" type="file" name="photo">
                                    <img width="100" id="preview" height="100" src="{{$section->image}}" alt="">
                                </div>
                            </div>
                        </div>

                        <hr>
                        {{--                            <button id="add_type_btn" class="btn btn-warning"><i class="fa fa-plus"></i> إضافه نوع جديد--}}
                        {{--                            </button>--}}

                        <h3>لماذا تختارنا</h3>
                        <br>

                        <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>العنوان</th>
                                    <th>المحتوي</th>
                                    <th>الصورة</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($section->types as $index => $type)
                                @php
                                $index +=1;
                                @endphp
                                <tr>
                                    <td>
                                        <div class="input-custom">
                                            <input type="hidden" name="type[{{$index}}][id]" value="{{$type->id}}">
                                            <input type="text" value="{{$type->name}}" class="form-control"
                                                name="type[{{$index}}][name]">
                                        </div>
                                    </td>
                                    <td>
                                        <div class="input-custom">
                                            <input type="text" value="{{$type->content}}" class="form-control"
                                                name="type[{{$index}}][content]">
                                        </div>
                                    </td>
                                    <td>
                                        <div class="input-custom">
                                            <input type="file" id="photo" class="photo" name="type[{{$index}}][photo]">
                                        </div>
                                    </td>
                                    <td>
                                            <img width="100" id="preview" height="100" src="{{$type->image}}" alt="">
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>

                        </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="btn ripple btn-primary" type="submit"><i class="fe fe-save"></i> حفظ</button>
                    </div>
                </div>
            </form>

        </div>
    </div> <!-- End Main Content-->
</div> <!-- End Page -->
@endsection
@push('js')
<script>
    let count = '{{count($section->types)}}';
    count = ++count;



    // $('#add_type_btn').on('click', function (e) {
    //     e.preventDefault();
    //     if (count > 5) {
    //         Swal.fire({
    //             icon: 'error',
    //             title: 'عذراً ...',
    //             text: 'عدد الأنواع لابد أن يكون مساوياً  ل5  أو أقل !',
    //
    //         });
    //     } else {
    //         let content = `
    //     <div class="card-content">
    //         <i class="fa fa-times delete_card"></i>
    //         <div class="row">
    //             <div class="col-md-6">
    //                 <div class="input-custom">
    //                     <input type="text" class="form-control" name="type[${count}][name]">
    //                     <span class="input-span">الاسم</span>
    //                 </div>
    //             </div>
    //             <div class="col-md-6">
    //             <div class="row">
    //                 <div class="col-md-6">
    //                     <div class="input-custom">
    //                         <input type="file" class="form-control" name="type[${count}][photo]">
    //                          <span class="input-span">الصوره</span>
    //                      </div>
    //                 </div>
    //                 <div class="col-md-6"></div>
    //             </div>
    //
    //             </div>
    //             <div class="col-md-12">
    //                 <div class="input-custom">
    //                     <input type="text" class="form-control" name="type[${count}][content]">
    //                     <span class="input-span">المحتوي</span>
    //                 </div>
    //             </div>
    //         </div>
    //     </div>
    //
    // `;
    //         $('#add_new_type').append(content);
    //         count++
    //
    //
    //         console.log(count)
    //     }
    // });


    // $(document).on('click', '.delete_card', function () {
    //     Swal.fire({
    //         title: 'هل أنت متأكد',
    //         text: "",
    //         icon: 'warning',
    //         showCancelButton: true,
    //         confirmButtonColor: '#3085d6',
    //         cancelButtonColor: '#d33',
    //         confirmButtonText: 'نعم',
    //         cancelButtonText: 'لا'
    //     }).then((result) => {
    //         if (result.isConfirmed) {
    //             $(this).parent().remove();
    //
    //             count--
    //             count = count < 1 ? 1 : count;
    //
    //         }
    //     });
    //
    // });

</script>
@endpush

resources/views/dashboard/sections/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">
                <div class="card">
                    <div class="card-header">
                        <h3>السكاشن</h3>
                        <div class="flex-btns">
{{--                            <a href="" id="delete_all_btn" class="btn ripple btn-danger d-none"><i class="fe fe-trash"></i> حذف الكل </a>--}}
{{--                            <a href="{{route('sections.create')}}" class="btn ripple btn-primary"><i class="fe fe-plus"></i> اضافة </a>--}}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <form id="bulk_delete" action="{{route('sections.bulkDelete')}}" method="post">
                                @csrf
                                <table class="table datatable table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>
                                            <input type="checkbox" id="check_all">
                                        </th>
                                        <th>#</th>
                                        <th>العنوان</th>
                                        <th>الصورة</th>
                                        <th>العمليات</th>
                                    </tr>
                                    </thead>


                                    <tbody>


                                    </tbody>

                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->

@endsection
@push('js')
    <script>
        var table = $('.table.datatable').DataTable({
            lengthChange: true,

            "processing": true,
            "serverSide": true,
            "ajax": {
                url: '{{route('sections.data')}}',

            },
            "columns": [
                {data: 'check_item', name: 'check_item', sortable: false, searchable: false},
                {data: 'id', name: 'id'},
                {data: 'title', name: 'title'},
                {data: 'photo', name: 'photo'},
                {data: 'actions', name: 'actions'}
            ]


        });

    </script>
@endpush