routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard.index');

    // profile
    Route::get('/profile', 'HomeController@profile')->name('user.profile');
    Route::post('/profile', 'HomeController@editProfile')->name('user.editProfile');

    // end profile

    // sliders routes
    Route::get('sliders-data', 'SliderController@data')->name('sliders.data');
    Route::post('sliders-bulkDelete', 'SliderController@bulkDelete')->name('sliders.bulkDelete');
    Route::resource('sliders', 'SliderController')->except('show');
    //end sliders routes

    // about routes
    Route::get('about-data', 'AboutController@data')->name('about.data');
    Route::post('about-bulkDelete', 'AboutController@bulkDelete')->name('about.bulkDelete');
    Route::resource('about', 'AboutController')->except('show');
    //end about routes

    // customers routes
    Route::get('customers-data', 'CustomerController@data')->name('customers.data');
    Route::post('customers-bulkDelete', 'CustomerController@bulkDelete')->name('customers.bulkDelete');
    Route::resource('customers', 'CustomerController')->except('show');
    //end customers routes

    // blogs routes
    Route::get('blogs-data', 'BlogController@data')->name('blogs.data');
    Route::post('blogs-bulkDelete', 'BlogController@bulkDelete')->name('blogs.bulkDelete');
    Route::resource('blogs', 'BlogController')->except('show');
    //end customers routes

    // services routes
    Route::get('services-data', 'ServiceController@data')->name('services.data');
    Route::post('services-bulkDelete', 'ServiceController@bulkDelete')->name('services.bulkDelete');
    Route::resource('services', 'ServiceController')->except('show');
    //end services routes

    // projects routes
    Route::get('projects-data', 'ProjectController@data')->name('projects.data');
    Route::post('projects-bulkDelete', 'ProjectController@bulkDelete')->name('projects.bulkDelete');
    Route::resource('projects', 'ProjectController')->except('show');
    //end projects routes

    // contact routes
    Route::get('contact-us-data', 'ContactUsController@data')->name('contact-us.data');
    Route::post('contact-us-bulkDelete', 'ContactUsController@bulkDelete')->name('contact-us.bulkDelete');
    Route::resource('contact-us', 'ContactUsController')->except('show');
    //end contact routes

    // sections
    Route::get('sections-data', 'SectionController@data')->name('sections.data');
    Route::post('sections-bulkDelete', 'SectionController@bulkDelete')->name('sections.bulkDelete');
    Route::resource('sections', 'SectionController')->except('show');
    // end sections

    //pages
    Route::get('pages-data', 'PageController@data')->name('pages.data');
    Route::resource('pages', 'PageController')->except('show');
    //end pages

    // settings
    Route::get('settings', 'SettingController@index')->name('settings.index');
    Route::post('settings', 'SettingController@store')->name('settings.store');
    // end settings


});

routes/web.php
<?php

use App\Models\Page;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::namespace('website')->group(function () {

    // home
    Route::get('/', 'FrontController@index')->name('home');
    // end home

    // about
    Route::get('about', 'AboutController@index');
    // end about

    // services
    Route::get('services', 'ServiceController@index');
    Route::get('services/{id}', 'ServiceController@show');
    // end services

    // projects
    Route::get('projects', 'ProjectController@index');
    Route::get('projects/{id}', 'ProjectController@show');
    // end projects

    // blogs
    Route::get('blogs', 'BlogController@index');
    Route::get('blogs/{id}', 'BlogController@show');
    // end blogs

    //contact us
    $page_name = Page::where('url','/contact-us')->first()->name;
    Route::view('contact-us', 'website.pages.contact_us.index',compact('page_name'));
    Route::post('contact-us', 'ContactUsController@post')->name('website.contactUs');
    // end contact us
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $table = 'projects';
    protected $guarded = [];
    protected $with = 'photos';

    public function photos()
    {
        return $this->morphMany(Photo::class, 'photoable');
    }//end of  function
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Helper\UploadTrait;
use App\Http\Requests\ProjectRequest;
use App\Models\Project;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class ProjectController extends Controller
{
    use UploadTrait;

    public function index()
    {

        return view('dashboard.projects.index');
    }


    public function create()
    {
        return view('dashboard.projects.create');
    }

    public function data()
    {
        $model = 'projects';
        $projects = Project::with('photos')->get();
        return DataTables::of($projects)
            ->addColumn('check_item', function ($raw) {
                return '<input type="checkbox" name="items[]" class="check_item" value="' . $raw->id . '">';
            })
            ->addcolumn('actions', function ($raw) use ($model) {

                return view('dashboard.includes.actions', compact('raw', 'model'));
            })
            ->rawColumns(['check_item' => 'check_item'])
            ->make(true);

    }//end of data function


    public function store(ProjectRequest $request)
    {

        $data = $request->validated();

        unset($data['photos']);


        $project = Project::create($data);

        if ($request->hasFile('photos')) {
            $photos = $this->uploadAlbum($request->photos, 'projects');

            foreach ($photos as $photo) {

                $project->photos()->create([
                    'src' => $photo,
                    'type' => 'project',
                ]);
            }
        };

        return redirect()->route('projects.index')->with('success', 'تم إضافه البيانات بنجاح');

    }


    public function edit(Project $project)
    {
        return view('dashboard.projects.edit', compact('project'));
    }

    public function update(ProjectRequest $request, Project $project)
    {

        $data = $request->validated();
        unset($data['photos']);
        $project->update($data);
        if (!empty($request->old)) {
            $this->deleteOldAlbum('images/projects/', $project->photos, $request->old);
        } else {
            // delete all old photos
            $this->deleteAllOLdPhotos('images/projects', $project->photos);
        }
        if ($request->hasFile('photos')) {
            $photos = $this->uploadAlbum($request->photos, 'projects');

            foreach ($photos as $photo) {
                $project->photos()->create([
                    'src' => $photo,
                    'type' => 'project',
                ]);
            }
        }

        return redirect()->route('projects.index')->with('success', 'تم تعديل البيانات بنجاح');
    }


    public function destroy(Project $project)
    {
        $project->photos ? $this->deleteAlbum('images/projects/', $project->photos) & $project->photos()->delete() : '';
        Project::destroy($project->id);
        return redirect()->route('projects.index')->with('success', 'تم حذف البيانات بنجاح');
    }

    public function bulkDelete(Request $request)
    {
        foreach ($request->items as $item) {
            $project = Project::findOrFail($item);
            $this->destroy($project);
        }
        Project::destroy($request->items);
        return redirect()->route('projects.index')->with('success', 'تم حذف البيانات بنجاح');


    }//end of bulkDelete function

    public function deleteAlbum($path, $files)
    {

        foreach ($files as $file) {
            $this->deleteOldPhoto($path, $file->src);
        }

    }//end of deleteAlbum function
}

app/Http/Controllers/Website/ProjectController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Models\Page;
use App\Models\Project;

class ProjectController extends Controller
{
    public function index()
    {
        $page_name = Page::where('url','/projects')->first()->name;
        $projects = Project::get();
        return view('website.pages.projects.index', compact('projects','page_name'));

    }//end of index function

    public function show($id)
    {
        $page_name = Page::where('url','/projects')->first()->name;
        $project = Project::findOrFail($id);
        $projects = Project::select(['id', 'title'])->where('id', '!=', $id)->get()->take(3);


        return view('website.pages.projects.show', compact('project', 'projects','page_name'));
    }//end of show function
}

resources/views/dashboard/projects/create.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">

                <form action="{{route('projects.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <h3>إضافه مشروع</h3>
                        </div>
                        <div class="card-body pb-0">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input value="{{old('title')}}" type="text" name="title" class="form-control">
                                        <span class="input-span">العنوان</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input value="{{old('customer')}}" type="text" name="customer" class="form-control">
                                        <span class="input-span">العميل</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <textarea name="content" rows="3" class="form-control editor">{{old('content')}}</textarea>
                                        <span class="input-span">المحتوي</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input type="date" value="{{old('end_date')}}" name="end_date" class="form-control">
                                        <span class="input-span">تاريخ الانتهاء</span>
                                    </div>
                                </div>
                            </div>
                            <div class="input-custom">
                                <span class="input-span">الصور ( مقاس الصورة -- 800 طول * 1200 عرض )</span>
                                <div class="input-images"></div>
                            </div>

                            <div class="accordion-container">
                                <div class="set">
                                    <a href="#">
                                        بيانات السيو SEO
                                        <i class="fa fa-plus"></i>
                                    </a>
                                    <div class="box-custom">
                                        <div class="flex-divs">
                                            <div class="input-custom">
                                                <input value="" type="text" name="meta_title" class="form-control">
                                                <span class="input-span">عنوان الميتا</span>
                                            </div>
                                            <div class="input-custom">
                                                <input value="" type="text" name="meta_keywords" class="form-control">
                                                <span class="input-span">الكلمات الدلالية</span>
                                            </div>
                                            <div class="input-custom">
                                                <textarea name="meta_description" class="form-control editor"></textarea>
                                                <span class="input-span">وصف الميتا</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button class="btn ripple btn-primary" type="submit"><i class="fe fe-save"></i> حفظ</button>
                        </div>
                    </div>
                </form>

            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->
@endsection
@push('js')
    <script>


        $('.input-images').imageUploader({
            imagesInputName: 'photos',
            preloadedInputName: 'old',
            maxSize: 2 * 1024 * 1024,
            maxFiles: 10
        });
    </script>
@endpush

resources/views/dashboard/projects/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">

                <form action="{{route('projects.update',$project->id)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="card">
                        <div class="card-header">
                            <h3>إضافه مشروع</h3>
                        </div>
                        <div class="card-body pb-0">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input value="{{$project->title}}" type="text" name="title" class="form-control">
                                        <span class="input-span">العنوان</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input value="{{$project->customer}}" type="text" name="customer" class="form-control">
                                        <span class="input-span">العميل</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <textarea name="content" rows="3" class="form-control editor">{{$project->content}}</textarea>
                                        <span class="input-span">المحتوي</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">

                                        <input type="date" value="{{$project->end_date}}" name="end_date" class="form-control">
                                        <span class="input-span">تاريخ الانتهاء</span>
                                    </div>
                                </div>
                            </div>
                            <div class="input-custom">
                                <span class="input-span">الصور ( مقاس الصورة -- 800 طول * 1200 عرض )</span>
                                <div class="input-images"></div>
                            </div>

                            <div class="accordion-container">
                                <div class="set">
                                    <a href="#">
                                        بيانات السيو SEO
                                        <i class="fa fa-plus"></i>
                                    </a>
                                    <div class="box-custom">
                                        <div class="flex-divs">
                                            <div class="input-custom">
                                                <input value="{{$project->meta_title}}" type="text" name="meta_title" class="form-control">
                                                <span class="input-span">عنوان الميتا</span>
                                            </div>
                                            <div class="input-custom">
                                                <input value="{{$project->meta_keywords}}" type="text" name="meta_keywords" class="form-control">
                                                <span class="input-span">الكلمات الدلالية</span>
                                            </div>
                                            <div class="input-custom">
                                                <textarea name="meta_description" class="form-control editor">{!! $project->description !!}</textarea>
                                                <span class="input-span">وصف الميتا</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button class="btn ripple btn-primary" type="submit"><i class="fe fe-save"></i> حفظ</button>
                        </div>
                    </div>
                </form>

            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->

@endsection

@push('js')
    <script>


        $('.input-images').imageUploader({
            preloaded:  {!! getProjectAlbum($project->id) !!},
            imagesInputName: 'photos',
            preloadedInputName: 'old',
            maxSize: 2 * 1024 * 1024,
            maxFiles: 10,
            delete: function () {
                alert('asd')
            }

        });
    </script>
@endpush

resources/views/dashboard/projects/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">
                <div class="card">
                    <div class="card-header">
                        <h3>مشاريعنا</h3>
                        <div class="flex-btns">
                            <a href="" id="delete_all_btn" class="btn ripple btn-danger d-none"><i class="fe fe-trash"></i> حذف الكل </a>
                            <a href="{{route('projects.create')}}" class="btn ripple btn-primary"><i class="fe fe-plus"></i> اضافة </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <form id="bulk_delete" action="{{route('projects.bulkDelete')}}" method="post">
                                @csrf
                                <table class="table datatable table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>
                                            <input type="checkbox" id="check_all">
                                        </th>
                                        <th>#</th>
                                        <th>العنوان</th>
                                        <th>العمليات</th>
                                    </tr>
                                    </thead>


                                    <tbody>


                                    </tbody>

                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->

@endsection
@push('js')
    <script>
        var table = $('.table.datatable').DataTable({
            lengthChange: true,

            "processing": true,
            "serverSide": true,
            "ajax": {
                url: '{{route('projects.data')}}',

            },
            "columns": [
                {data: 'check_item', name: 'check_item', sortable: false, searchable: false},
                {data: 'id', name: 'id'},
                {data: 'title', name: 'title'},
                {data: 'actions', name: 'actions'}
            ]


        });

    </script>
@endpush